### PR TITLE
Upgraded ember-cli, ember and related to the latest

### PR DESCRIPTION
**Pull request by kasunvp**
@lukemelia @mminkoff @kmiyashiro @ChALkeR
Hey guys sorry to ping you all but not sure who is active here on this.

We're using this addon in our project and would like to get this upgraded and updated. 
For everyone's convenience, I have already upgraded ember-cli, ember, etc. in this PR. if it looks good hope we can get this merged?

Thanks.

### CODE REVIEW

**Comment by yonida** [comment]
good luck!

**Comment by kasunvp** [comment]
@yonida thanks. Can you do a publish to npm? Also any idea in making a release?

**Comment by yonida** [comment]
@kasunvp done.

**Comment by kasunvp** [comment]
Thanks @yonida

**Pull request merged**
